.TH GIT-GUD 1 "19 Feb 2020"
.SH NAME
git-gud \- get good at git with git-gud
.SH SYNOPSIS
.B git gud
[option1] [option2]
.SH DESCRIPTION
.B git-gud
teaches you how to use Git with fun interactive tutorials.
.TP
Use the following command to creates a Git repository and start the first level:
.B python\ \-m\ gitgud\ start
