version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Level synthesis test
          command: |
            echo -e "y\n" | python ./make_level.py testlevel1 "Test Level 1" testskill "Test Skill"
            echo -e "y\n" | python ./make_level.py testlevel2 "Test Level 2" testskill
      - run:
          name: Set up environment
          command: |
            pip install .
            pip install pytest
            pip install flake8
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
      - run:
          name: Running tests
          command: |
            export PATH=$PATH:$HOME/.local/bin
            python -m pytest gitgud
      - run:
          name: flake8 checks
          command: |
            python -m flake8 .

